### ISSUE TITLE
Add cache optimization

### ISSUE THREAD

**Issue by ouhenio** [ouhenio/en2ru-DALLE-notebook#2]
It would be a good idea to include the code from [this issue](https://github.com/sberbank-ai/ru-dalle/pull/12) of the original repo to speed up the generation process.

**Comment by johnpaulbin** [comment]
It speeds it up greatly, highly recommended

**Comment by johnpaulbin** [comment]
seems it has been merged to master now, should work out of the box.

**Comment by ouhenio** [comment]
> 
> 
> seems it has been merged to master now, should work out of the box.

It does! Thank you for your help. 😊
